--- Busted tests for pipe-line pipe object
describe("pipe-line.pipe", function()
	local Pipe

	before_each(function()
		package.loaded["pipe-line.pipe"] = nil
		Pipe = require("pipe-line.pipe")
	end)

	describe("new", function()
		it("does not copy methods onto instance", function()
			local p = Pipe.new({ "a", "b" })
			assert.is_nil(rawget(p, "splice"))
			assert.is_nil(rawget(p, "clone"))
			assert.is_function(p.splice)
			assert.is_function(p.clone)
		end)

		it("creates array from entry", function()
			local p = Pipe.new({ "a", "b", "c" })
			assert.are.equal(3, #p)
			assert.are.equal("a", p[1])
			assert.are.equal("b", p[2])
			assert.are.equal("c", p[3])
		end)

		it("starts with rev 0", function()
			local p = Pipe.new({ "a" })
			assert.are.equal(0, p.rev)
		end)

		it("starts with empty splice_journal", function()
			local p = Pipe.new({ "a" })
			assert.are.equal(0, #p.splice_journal)
		end)

		it("handles empty entry", function()
			local p = Pipe.new({})
			assert.are.equal(0, #p)
			assert.are.equal(0, p.rev)
		end)
	end)

	describe("splice", function()
		it("inserts element", function()
			local p = Pipe.new({ "a", "c" })
			p:splice(2, 0, "b")
			assert.are.equal(3, #p)
			assert.are.equal("a", p[1])
			assert.are.equal("b", p[2])
			assert.are.equal("c", p[3])
		end)

		it("deletes element", function()
			local p = Pipe.new({ "a", "b", "c" })
			local deleted = p:splice(2, 1)
			assert.are.equal(2, #p)
			assert.are.equal("a", p[1])
			assert.are.equal("c", p[2])
			assert.are.equal(1, #deleted)
			assert.are.equal("b", deleted[1])
		end)

		it("replaces element", function()
			local p = Pipe.new({ "a", "b", "c" })
			p:splice(2, 1, "x", "y")
			assert.are.equal(4, #p)
			assert.are.equal("a", p[1])
			assert.are.equal("x", p[2])
			assert.are.equal("y", p[3])
			assert.are.equal("c", p[4])
		end)

		it("increments rev", function()
			local p = Pipe.new({ "a" })
			assert.are.equal(0, p.rev)
			p:splice(1, 0, "b")
			assert.are.equal(1, p.rev)
			p:splice(1, 0, "c")
			assert.are.equal(2, p.rev)
		end)

		it("records journal entry", function()
			local p = Pipe.new({ "a", "b" })
			p:splice(2, 0, "x", "y")
			assert.are.equal(1, #p.splice_journal)
			local entry = p.splice_journal[1]
			assert.are.equal(1, entry.rev)
			assert.are.equal(2, entry.start)
			assert.are.equal(0, entry.deleted)
			assert.are.equal(2, entry.inserted)
		end)
	end)

	describe("clone", function()
		it("creates independent copy", function()
			local p = Pipe.new({ "a", "b", "c" })
			local c = p:clone()
			assert.are.equal(3, #c)
			assert.are.equal("a", c[1])

			c:splice(1, 1)
			assert.are.equal(2, #c)
			assert.are.equal(3, #p) -- original unchanged
		end)

		it("inherits rev from parent", function()
			local p = Pipe.new({ "a" })
			p:splice(1, 0, "b")
			assert.are.equal(1, p.rev)
			local c = p:clone()
			assert.are.equal(1, c.rev)
		end)

		it("starts with fresh journal", function()
			local p = Pipe.new({ "a" })
			p:splice(1, 0, "b")
			local c = p:clone()
			assert.are.equal(0, #c.splice_journal)
		end)
	end)
end)
